### ISSUE TITLE
报错54001，请检查您的签名生成方法

### ISSUE THREAD

**Issue by cy3486** [NumberSir/nonebot_plugin_baidutranslate#2]
![image](https://user-images.githubusercontent.com/37792034/196571796-d312f879-6af4-40e9-b165-97ef443e1af9.png)

虽然我觉得你的签名生成方法没什么问题..
↑所以我也不知道怎么改了

os: win server 2016 standard
python ver: 3.9.2

**Comment by cy3486** [comment]
os: win server 2016 standard
python ver: 3.9.2

**Comment by NumberSir** [comment]
> ![image](https://user-images.githubusercontent.com/37792034/196571796-d312f879-6af4-40e9-b165-97ef443e1af9.png)
> 
> 虽然我觉得你的签名生成方法没什么问题.. ↑所以我也不知道怎么改了
> 
> os: win server 2016 standard python ver: 3.9.2

看看是不是appid或apikey填错了

**Comment by cy3486** [comment]
> > ![image](https://user-images.githubusercontent.com/37792034/196571796-d312f879-6af4-40e9-b165-97ef443e1af9.png)
> > 虽然我觉得你的签名生成方法没什么问题.. ↑所以我也不知道怎么改了
> > os: win server 2016 standard python ver: 3.9.2
> 
> 看看是不是appid或apikey填错了

没填错欸    佬

**Comment by NumberSir** [comment]
我自己使用是正常的，签名生成方法是对的。
试了一下，如果apikey填错了会出现54001错误。你再看看

**Comment by cy3486** [comment]
> 我自己使用是正常的，签名生成方法是对的。 试了一下，如果apikey填错了会出现54001错误。你再看看

貌似就是我填错了...尴尬   
谢谢大佬   给大佬添麻烦辣
